### PR TITLE
Moved contextIdReducer, groupsDataReducer, groupsIndexReducer to wa tool codebase

### PR DESCRIPTION
**Pull request by mannycolon**
## Describe what your pull request addresses (Please include relevant issue numbers):
-

## Please include detailed Test instructions for your pull request:
- ### DO NOT MERGE UNTIL ALL PRs ARE READY TO BE MERGED 
- In translationCore repo checkout `feature-mannycolon-6501`
- run `rm -rf node_modules`  & `npm i`
- cd `tC_apps/wordAlignment` & checkout `feature-mannycolon-6501`
- Open the app and test thoroughly  
- tN, Tw & wA tools should all work correctly

### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/wordalignment/245)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
@mannycolon - LGTM code review.

**Comment by PhotoNomad0** [comment]
@mannycolon - in testing, for WA comments it looks like when you change contextID, it is reading the comment from the oldest timestamp, not the most recent.

**Comment by PhotoNomad0** [comment]
It does seem to be saving the latest comment to the file system, but they seem to be ignored.

**Comment by PhotoNomad0** [comment]
@mannycolon - it looks like /translationCore/projects/en_alcz_tit_book/.apps/translationCore/index/wordAlignment/tit/chapter_3.json is not being updated when comments are changed.

**Comment by PhotoNomad0** [comment]
It looks like on contextId change the comments are read from groupsDataReducer, but all the toggles for changing the groupsDataReducer have been removed.  So the groups data is not being updated with new comments and bookmarks.

**Comment by mannycolon** [comment]
@PhotoNomad0 Bruce you implemented the commentsReducer, didnt you create the data loading? if you did it should not be necessary to have TOGGLE_COMMENTS_IN_GROUPDATA?

**Comment by PhotoNomad0** [comment]
@mannycolon - that's what loadNewContext() did, but it is not being called anymore.  Did you try to replicate that behavior elsewhere?

**Comment by PhotoNomad0** [comment]
Ahh - moved contextId reducer into tool, so no longer get notification toolWillReceiveProps() whenever contextId changes.

**Comment by PhotoNomad0** [comment]
@mannycolon - looks like changeContextIdInReducers() needs to be changed to do something similar to loadNewContext instead of loading reducers with old data in groupsDataReducer.

**Comment by PhotoNomad0** [comment]
Fixes previous problem.  Now missing lexicon:

Screen Shot 2020-02-12 at 8 09 18 AM

**Comment by PhotoNomad0** [comment]
In stepping through the lexicon call, it looks like some methods have been moved in tC.  In ToolsContainer I see this.  Looks like These methods were rewritten and are not returning values anymore:

```
const mapDispatchToProps = (dispatch) => ({
...
  getLexiconData(lexiconId, entryId) {
    getLexiconData(lexiconId, entryId);
  },
  getAvailableScripturePaneSelections(resourceList) {
    getAvailableScripturePaneSelections(resourceList);
  },
...
});
```

**Comment by mannycolon** [comment]
@PhotoNomad0 Fixed

**Comment by PhotoNomad0** [comment]
Seeing error in console:

Screen Shot 2020-02-12 at 9 49 45 AM

This happens when I select a project.  Looks like a problem in tC getGroupsData() when check is not found, this throws an exception:

```
              const { selections } = loadCheckData(loadPath, groupDataItem.contextId);
```

**Comment by PhotoNomad0** [comment]
It looks like an old bug that is not failing gracefully.  Throwing an exception when dereferencing an undefined value rather than setting that selection to false.

**Comment by PhotoNomad0** [comment]
@mannycolon - in WA tool, in enhanced scripture pane, editing the verse does not change the verse.

**Comment by mannycolon** [comment]
@PhotoNomad0 Fixed the expanded scripture pane verse edit functionality

**Pull request merged**
